# Generated by Django 5.1.7 on 2025-03-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_demographics_age_alter_demographics_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (Little to no exercise)'), ('moderate', 'Moderate (3-4 days a week)'), ('active', 'Active (Daily intense workouts)')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='fitness_goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Improve Endurance'), ('general_fitness', 'General Fitness')], default='general_fitness', max_length=20),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='height',
            field=models.FloatField(default=170.0, help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='weight',
            field=models.FloatField(default=70.0, help_text='Weight in kg'),
        ),
    ]
