# Generated by Django 5.1.7 on 2025-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_demographics_activity_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('fitness_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Improve Endurance'), ('general_fitness', 'General Fitness')], default='general_fitness', max_length=20)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (Little to no exercise)'), ('moderate', 'Moderate (3-4 days a week)'), ('active', 'Active (Daily intense workouts)')], default='moderate', max_length=20)),
                ('target_age_min', models.PositiveIntegerField(default=18)),
                ('target_age_max', models.PositiveIntegerField(default=60)),
                ('target_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('any', 'Any')], default='any', max_length=10)),
                ('target_bmi_min', models.FloatField(default=18.5, help_text='Minimum BMI for this workout')),
                ('target_bmi_max', models.FloatField(default=30.0, help_text='Maximum BMI for this workout')),
            ],
        ),
    ]
