# Generated by Django 5.1.7 on 2025-03-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
