# Generated by Django 5.2.1 on 2025-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_remove_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(help_text='10-digit phone number', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='10-digit phone number', max_length=10),
        ),
    ]
