# Generated by Django 5.2.1 on 2025-05-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='workout_difficulty',
            field=models.CharField(blank=True, help_text='Difficulty level of the workout', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='workout_name',
            field=models.CharField(blank=True, help_text="Name of the workout if activity_type is 'workout'", max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('flexibility', 'Flexibility'), ('workout', 'Workout'), ('other', 'Other')], max_length=20),
        ),
    ]
